[general]
  loglevel = "notice"
  hosts = ["carbonio"]
  default_server_domain = "carbonio"
  language = "en"
  rdbms_server_type = "pgsql"

[auth]
  methods = ["http"]
  password.format = "plain"
  sasl_mechanisms = ["plain"]
  [auth.http]

[outgoing_pools.http.auth]
  connection.host = "http://127.78.0.10:10001"

[s2s]
  default_policy = "deny"
[outgoing_pools.rdbms.default]
  scope = "global"
  workers = 5

  [outgoing_pools.rdbms.default.connection]
    driver = "pgsql"
    host = "127.78.0.10"
    port = 20000
    database = "carbonio-chats-messaging-db"
    username = "carbonio-chats-messaging-db"
    password = "<insert-password>"

[listen]
  [[listen.c2s]]
    port = 10000
    ip_address = "127.78.0.11"

  [[listen.http]]
    port = 10000
    ip_address = "127.78.0.10"
    transport.num_acceptors = 10
    transport.max_connections = 1024

    [[listen.http.handlers.mod_websockets]]
      host = "_"
      path = "/ws-xmpp"
      ping_rate = 30_000

    [[listen.http.handlers.mongoose_api_admin]]
      host = "_"
      path = "/admin"

    [[listen.http.handlers.mongoose_client_api_messages]]
      host = "_"
      path = "/api/messages/[:with]"

    [[listen.http.handlers.mongoose_client_api_contacts]]
      host = "_"
      path = "/api/contacts/[:jid]"

    [[listen.http.handlers.mongoose_client_api_rooms]]
      host = "_"
      path = "/api/rooms/[:id]"

    [[listen.http.handlers.mongoose_client_api_rooms_config]]
      host = "_"
      path = "/api/rooms/[:id]/config"

    [[listen.http.handlers.mongoose_client_api_rooms_users]]
      host = "_"
      path = "/api/rooms/:id/users/[:user]"

    [[listen.http.handlers.mongoose_client_api_rooms_messages]]
      host = "_"
      path = "/api/rooms/[:id]/messages"

[modules.mod_muc_light]
  backend = "rdbms"
  host = "muclight.@HOST@"
  equal_occupants = true
  all_can_configure = true
  all_can_invite = true
[modules.mod_disco]
  users_can_see_hidden_services = true
[modules.mod_mam_meta]
  backend = "rdbms"
  muc.backend = "rdbms"
  muc.host = "muclight.@HOST@"
  #This is a plain format due to the possible future messages migration from chats to mongooseim, if you find a way to
  #migrate them that will actually save them in other formats like mam_message_eterm or mam_message_compressed_eterm,
  #use those
  db_message_format="mam_message_xml"

[modules.mod_commands]
[modules.mod_muc_commands]
[modules.mod_muc_light_commands]
[modules.mod_inbox]
  reset_markers = ["displayed"]
  groupchat = ["muclight"]
[modules.mod_last]
  backend = "rdbms"
[modules.mod_offline_stub]
[modules.mod_roster]
  backend = "rdbms"
[modules.mod_carboncopy]
[modules.mod_ping]
[modules.mod_smart_markers]
  backend = "rdbms"